config/routes.rb
Rails.application.routes.draw do

  resources :stories

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :story
  acts_as_list :scope => :story
end

app/models/story.rb
class Story < ActiveRecord::Base

  validates :title, :summary, :presence => true
  has_many :resources, -> { order("position ASC") }, :dependent => :delete_all
  accepts_nested_attributes_for :resources, :allow_destroy => true, :reject_if => :is_empty?
  
  def is_empty?(attributed)
    attributed['body'].length == 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
    @story = Story.new
    @story.resources.build
  end

  def create
    @story = Story.new story_params
    if @story.save
      redirect_to @story
    end
  end
  
  def show
    @story = Story.find(params[:id])
  end

  def edit
    @story = Story.find params[:id]
    @story.resources.build
  end

  def update
    @story = Story.find params[:id]
    if @story.update story_params
      redirect_to @story
    end
  end

  def delete
  end
  
  private
  
  def story_params
    params.require(:story).permit(:title, :summary, :resources_attributes => [:body, :type, :_destroy, :id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthoringApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/stories/_form.html.erb
<div class="row">
  <%= form_for @story do |f| %>
  <div class="six columns">
    <%= f.label :title %>
    <%= f.text_field :title, class: "u-full-width" %>
  </div>
  <div class="eight columns">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "u-full-width" %>
  </div>
  
  <div class="ten columns">
    <%= f.label :body %>
    <%= f.nested_fields_for :resources do |ff| %>
      <%= ff.text_area :body, class: "u-full-width" %>
      <%= ff.remove_nested_fields_link %>
    <% end %>
    <%= f.add_nested_fields_link :resources %>
  </div>
  
  <div class="twelve columns">
    <%= f.submit "Submit" %>
  </div>
  

  <% end %>
</div>

app/views/stories/edit.html.erb
<div class="row">
  <div class="twelve columns">
    <h1>new story</h1>
  </div>
</div>

<%= render "form" %>

app/views/stories/new.html.erb
<div class="row">
  <div class="twelve columns">
    <h1>new story</h1>
  </div>
</div>

<%= render "form" %>

app/views/stories/show.html.erb
Hello <%= @story.title %>

<% @story.resources.each do |resource| %>
<div class="resource">
  <%= simple_format resource.body %>
</div>
<% end %>

<%= link_to "edit", edit_story_path %>